# Generated by Django 3.0.3 on 2021-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('original_year', models.IntegerField(null=True)),
                ('no_songs', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('edition', models.CharField(blank=True, choices=[('O', 'Original'), ('RE', 'Reissue')], max_length=2)),
                ('condition', models.CharField(blank=True, choices=[('M', 'Mint'), ('NM', 'Near-Mint'), ('VG', 'Very-Good'), ('G', 'Good'), ('P', 'Poor')], max_length=2)),
                ('submission_date', models.DateTimeField()),
                ('genre', models.ManyToManyField(blank=True, to='vinyls.Genre')),
            ],
        ),
    ]
