# Generated by Django 3.0.3 on 2022-06-07 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinyls', '0002_vinyl_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
