# Generated by Django 3.0.3 on 2022-06-07 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinyls', '0003_vinyl_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='owner',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
